### ISSUE TITLE
stm32l051k8u6 has 64kb of flash but is configured with 16kb

### ISSUE THREAD

**Issue by azerupi** [stm32-rs/stm32l0xx-hal#170]
Hi!

Unless I'm missing something, I think that the memory descriptions loaded are not always correct? I'm using for example a `stm32l051k8u6` and `stm32l071k8u6`. According to the `Cargo.toml` of this hal it should activate the following features:
```toml
mcu-STM32L051K8Ux = ["stm32l0x1", "ufqfpn32", "io-STM32L051", "eeprom-2048"]

# Or

mcu-STM32L071K8Ux = ["stm32l0x1", "ufqfpn32", "io-STM32L071", "eeprom-3072"]
```

So they both fall under the `stm32l0x1` group and that loads `memory_l0x1.x` according to the build.rs file. This defines that there is `16kb` of flash. However on both of those MCUs the flash should be `64kb` according to the datasheet.
```
MEMORY
{     
    FLASH : ORIGIN = 0x08000000, LENGTH = 16K     
    RAM : ORIGIN = 0x20000000, LENGTH = 2K
}
```

![Screenshot from 2021-06-10 10-35-23](https://user-images.githubusercontent.com/7647338/121492954-a2b73780-c9d7-11eb-9d92-c2d31bb56196.png)
![Screenshot from 2021-06-10 10-35-06](https://user-images.githubusercontent.com/7647338/121492956-a34fce00-c9d7-11eb-88b6-a0a911f6a7a0.png)

This causes some linking issues because the firmware is "too big" to fit in 16K although it works fine when I select the `stm32l0x3` feature.

1. Can I override the memory configuration in my code without changing this hal crate as a temporary workaround?
2. Can we have more granularity in the flash memory configurations?
